---
# tasks file for deploy_apache_website
- name: IP-address
  debug:
    var: ansible_enp0s3.ipv4.address

#  - name: Определение с какой системой имеем дело
#    debug:
#      var: ansible_os_family

- block: #========= for Ubuntu ===================
  - name: Инсталяция Apache WebServer для Debian
    become_user: root
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: Запуск WebServer на Debian
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

- block: #========= for RedHat ===================
  - name: Инсталяция Apache WebServer для RedHat
    become_user: root
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: Запуск WebServer на RedHat
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

- block: #=========== Static files ================
  - name: Загрузка директории со стартовой страницей WebSite на Ubuntu и RedHat
    copy: src={{ item }} dest={{ destin_folder }} mode=0555

  - name: Формирование index.html по шаблону переменных
    template: src=banner.j2 dest={{ destin_folder }}/index.html mode=0555
    notify:
      - Restart Apache Debian
      - Restart Apache RedHat
