---

- name: Остановка серверов
  hosts: CLIENTS
  gather_facts: no
  become: yes
  become_user: root

  tasks:
  - name: Выключение
#    command: /sbin/shutdown -h now
    shell: sleep 3 && poweroff
    async: 1
    poll: 0