---
- name: Проверка удалённых хостов
  hosts: CLIENTS
  become: yes
  gather_facts: false
  vars:
    plc: "/app"
    grps: httpserver
    user: httpserver


  tasks:
  - include_tasks: dir_check.yml
  - include_tasks: groups_check.yml

#  - name: ШАГ 3. Проверка наличия пользователей