- name: Первоначальная настройка сервера
  hosts: CLIENTS
  become: yes
  gather_facts: false
  vars:
    grps: "httpserver"
    usrs: "httpserver"

  tasks:
  - include_tasks: dir_create.yml
  - include_tasks: groups_create.yml
  - include_tasks: users_create.yml

