- name: Первоначальная настройка сервера
  hosts: CLIENTS
  become: yes
  gather_facts: false

  tasks:
  - include_tasks: dirs_create.yml
  - include_tasks: groups_create.yml
  - include_tasks: users_create.yml

