---
- name: Deploy PostgreSQL on pgs host
  hosts: pgs
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/dev/vault.yml
    - ../host_vars/pgs/vars.yml

  vars:
    postgres_password: "{{ vault_postgres_password }}"

  roles:
    - docker_setup
    - postgres
