# playbooks/prometheus-deploy.yml
---
- name: Deploy monitoring stack
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/dev/vault.yml
# playbooks/prometheus-deploy.yml
  
  roles:
    - docker_setup
    - node_exporter

- name: Deploy Postgres Exporter
  hosts: pgs
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/dev/vault.yml
    - ../group_vars/dev/vars.yml
    - ../host_vars/pgs/vars.yml
  
  roles:
    - postgres_exporter

- name: Deploy Nginx Exporter on k8s
  hosts: k8s
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/dev/vault.yml

  roles:
    - nginx_exporter

- name: Deploy JMX Exporter on k8s (Tomcat)
  hosts: k8s
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/dev/vault.yml
    - ../host_vars/k8s/vars.yml

  roles:
    - jmx_exporter

- name: Deploy Prometheus on metrics
  hosts: mtrcs
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/dev/vault.yml

  roles:
    - prometheus
