# roles/jmx_exporter/tasks/main.yml
---
- name: Create jmx_exporter directory
  file:
    path: /opt/jmx_exporter
    state: directory
    mode: '0755'


- name: Download jmx_exporter jar
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/1.0.1/jmx_prometheus_javaagent-1.0.1.jar
    dest: /opt/jmx_exporter/jmx_prometheus_javaagent.jar
    mode: '0644'


- name: Deploy jmx_exporter config (without hostPort for javaagent mode)
  copy:
    dest: /opt/jmx_exporter/config.yml
    content: |
      startDelaySeconds: 0
      ssl: false
      lowercaseOutputName: false
      lowercaseOutputLabelNames: false
      rules:
        - pattern: ".*"
    mode: '0644'

