---

- name: Запуск Apache сервера на Debian-Ubuntu
  hosts: UBU
  become: yes

  tasks:
  - name: Инсталяция Apache WebServer
    become_user: root
    apt:
      name: apache2
      state: present

  - name: Запуск  WebServer
    service: 
      name: apache2
      state: started
      enabled: yes

