---

- name: Запуск Apache сервера на Debian-Ubuntu
  hosts: CLIENTS
  become: yes

  vars:
    source_folder: ./static
    destin_folder: /var/www/html

  tasks:
  - name: IP-address
    debug:
      var: ansible_enp0s3.ipv4.address

#  - name: Определение с какой системой имеем дело
#    debug:
#      var: ansible_os_family

  - name: Инсталяция Apache WebServer для Debian
    become_user: root
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Инсталяция Apache WebServer для RedHat
    become_user: root
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Загрузка стартовой страницы WebSite на Ubuntu
#    copy: src={{ source_folder }} dest={{ destin_folder }} mode=0555
    copy: src={{ item }} dest={{ destin_folder }} mode=0555
    with_fileglob: "{{ source_folder }}/*.*"
#    notify: Restart Apache Debian

  - name: Загрузка стартовой страницы WebSite на RHCent
#    copy: src={{ source_folder }} dest={{ destin_folder }} mode=0555
    copy: src={{ item }} dest={{ destin_folder }} mode=0555
    with_fileglob: "{{ source_folder }}/*.*"

#    notify: Restart Apache RedHat
#    notify:
#      - Restart Apache Debian
#      - Restart Apache RedHat

  - name: Запуск WebServer на Debian
    service: 
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: Запуск WebServer на RedHat
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"


  handlers:
  - name: Restart Apache Debian
    service:
      name: apache2
      state: restarted

  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted