---

- name: Install Apache & nothing
  hosts: RHCent
#  remote_user: ilya
  become: yes
#  become_user: root

  tasks:
  - name: Install Apache WebServer
    become: yes
    become_user: root
    apt:
      name: httpd
      state: present

  - name: Start WebServer & enabled it
    service: name=httpd    state=started    enabled=yes